/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MkmStarRating {
        "currentRate": number;
        "maxStars": number;
        "starsColor": string;
    }
    interface MkmWip {
    }
}
declare global {
    interface HTMLMkmStarRatingElement extends Components.MkmStarRating, HTMLStencilElement {
    }
    var HTMLMkmStarRatingElement: {
        prototype: HTMLMkmStarRatingElement;
        new (): HTMLMkmStarRatingElement;
    };
    interface HTMLMkmWipElement extends Components.MkmWip, HTMLStencilElement {
    }
    var HTMLMkmWipElement: {
        prototype: HTMLMkmWipElement;
        new (): HTMLMkmWipElement;
    };
    interface HTMLElementTagNameMap {
        "mkm-star-rating": HTMLMkmStarRatingElement;
        "mkm-wip": HTMLMkmWipElement;
    }
}
declare namespace LocalJSX {
    interface MkmStarRating {
        "currentRate"?: number;
        "maxStars"?: number;
        "starsColor"?: string;
    }
    interface MkmWip {
    }
    interface IntrinsicElements {
        "mkm-star-rating": MkmStarRating;
        "mkm-wip": MkmWip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mkm-star-rating": LocalJSX.MkmStarRating & JSXBase.HTMLAttributes<HTMLMkmStarRatingElement>;
            "mkm-wip": LocalJSX.MkmWip & JSXBase.HTMLAttributes<HTMLMkmWipElement>;
        }
    }
}
